name: aps2s
channels:
  - conda-forge
  - defaults
dependencies:
  - xesmf=0.7.0
  - xarray
  - matplotlib
  - cartopy
  - numpy
  - netcdf4
  - pip 
  - pip:
      - "f90nml"
      - "docstring_parser"
